title: "Gavin Pereira"
author: "Gavin Pereira"
description: "Gavin Pereira. Professor. PhD W.Aust., MAppStats ANU, BCM (Hons) W.Aust., GCRC QUT"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "projects.md", title: "Projects"}
  - {file: "papers.md", title: "Pubs"}
  - {file: "periphery.md", title: "Periphery"}
  - {file: "pereira lab.md", title: "Pereira Lab"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto: ai@curtin.edu.au"}
  - {title: Github, icon: github, url: "https://github.com/gavinfpereira"}
  - {title: LinkedIn, icon: linkedin, url: "https://au.linkedin.com/in/gavin-pereira-b3b6631b?trk=people-guest_people_search-card"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/GavinFPereira"} 

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

# Google Analytics
google_analytics: G-7V5SXSVXK7
